server:
  port: 8081
  context-path: /sell
spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://192.168.2.70/:3306/sell

    username: root
    password: 123456
  jpa:
      show-sql: true
      database: MYSQL




#wechat:
#  mpAppId:ww
#  mpAppSecret:
#  mchId:
#  mchKey:
#  keyPath:
#  notifyUrl: